### ISSUE TITLE
Flatout doesn't work

### ISSUE THREAD

**Issue by 0x62797465** [Martyx00/ghinja#12]
INFO  REPORT: Analysis succeeded for file: file:///usr/bin/cat (HeadlessAnalyzer)  
Decompile.java:23: error: cannot find symbol
import ghidra.app.script.GatherParamPanel;
                        ^
  symbol:   class GatherParamPanel
  location: package ghidra.app.script
skipping /home/h/.binaryninja/repositories/community/plugins/Martyx00_ghinja/Decompile.java
ERROR REPORT SCRIPT ERROR: Decompile.java : The class could not be found. It must be the public class of the .java file: Decompile not found by 3f9c97 [1] (HeadlessAnalyzer) ghidra.app.script.GhidraScriptLoadException: The class could not be found. It must be the public class of the .java file: Decompile not found by 3f9c97 [1]
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:105)
	at ghidra.app.util.headless.HeadlessAnalyzer.runScriptsList(HeadlessAnalyzer.java:908)
	at ghidra.app.util.headless.HeadlessAnalyzer.analyzeProgram(HeadlessAnalyzer.java:1070)
	at ghidra.app.util.headless.HeadlessAnalyzer.processFileWithImport(HeadlessAnalyzer.java:1552)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithLoader(HeadlessAnalyzer.java:1734)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1675)
	at ghidra.app.util.headless.HeadlessAnalyzer.processWithImport(HeadlessAnalyzer.java:1759)
	at ghidra.app.util.headless.HeadlessAnalyzer.processLocal(HeadlessAnalyzer.java:460)
	at ghidra.app.util.headless.AnalyzeHeadless.launch(AnalyzeHeadless.java:127)
	at ghidra.GhidraLauncher.launch(GhidraLauncher.java:78)
	at ghidra.Ghidra.main(Ghidra.java:54)
Caused by: java.lang.ClassNotFoundException: Decompile not found by 3f9c97 [1]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1585)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1970)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at org.apache.felix.framework.Felix.loadBundleClass(Felix.java:2116)
	at org.apache.felix.framework.BundleImpl.loadClass(BundleImpl.java:986)
	at ghidra.app.script.JavaScriptProvider.loadClass(JavaScriptProvider.java:156)
	at ghidra.app.script.JavaScriptProvider.getScriptInstance(JavaScriptProvider.java:91)
	... 10 more
 
INFO  ANALYZING changes made by post scripts: file:///usr/bin/cat (HeadlessAnalyzer)  
INFO  REPORT: Post-analysis succeeded for file: file:///usr/bin/cat (HeadlessAnalyzer)  
INFO  REPORT: Save succeeded for: /cat (cat:/cat) (HeadlessAnalyzer)  
INFO  REPORT: Import succeeded (HeadlessAnalyzer)  
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows

**Comment by 0x62797465** [comment]
I should add more details:
Ghidra version: 11.0.3-1.1
Binary ninja version: 4.1.5396 (dev, personal)
Binary used: /bin/cat (reproducible with any binary)
